version: '3'
services:
  iris:
    container_name: vxnaid_biometric
    build :
      context : .
      dockerfile : Dockerfile
      args:
              DB_HOST: ${DB_HOST}
              DB_USER: ${DB_USER}
              DB_PASSWORD: ${DB_PASSWORD}
              DB_PORT: ${DB_PORT}
              DB_NAME: ${DATABASE}
    ports:
      - ${ADMIN_PORT}:24932
      - ${CLIENT_PORT}:25452
